# Generated by Django 5.0.1 on 2024-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_swiftapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiftapplication',
            name='account_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='account_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='bank_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='iban',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='swiftapplication',
            name='swift_bic_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
