# Generated by Django 5.0.1 on 2024-01-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_swiftapplication_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftapplication',
            name='bank_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
