# Generated by Django 5.0.1 on 2024-01-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_swiftapplication_bank_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesscustomer',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
