# Generated by Django 5.0.1 on 2024-01-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_bussinesscustomer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiftapplication',
            name='swiftbase_code',
        ),
    ]
