# Generated by Django 5.0.1 on 2024-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_swiftapplication_swiftbase_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinesscustomer',
            name='phone_number',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
