# Generated by Django 5.0.1 on 2024-01-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_chatsession_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftapplication',
            name='iban',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
